# Generated by Django 5.1.3 on 2024-12-18 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("batch", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title_eng", models.TextField()),
                ("img", models.ImageField(upload_to="media/")),
                ("title_guj", models.TextField()),
                ("active_deactivate", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeetOurFellowsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("department", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("ug_degree", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("post_graduation", models.CharField(max_length=255)),
                ("pg_university", models.CharField(max_length=255)),
                ("bachelore_degree", models.CharField(max_length=255)),
                ("ug_university", models.CharField(max_length=255)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.batchmodel"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
