# Generated by Django 5.1.4 on 2024-12-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediamodel",
            old_name="title",
            new_name="title_eng",
        ),
        migrations.AddField(
            model_name="mediamodel",
            name="active_deactivate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediamodel",
            name="title_guj",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
    ]
